### 
GET http://localhost:3000/user

###
GET http://localhost:3000/user/5dd3cfc8b6eb421d546751e6
###
DELETE http://localhost:3000/user/5dc915119f007d27782d1bfa
### SignUp
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name": "33333",
    "email": "test@api.nhe",
    "password": "wwww",
    "role": "user",
    "phone": ""
}

### verify
POST http://localhost:3000/verify/84383593e9ac9a44f9aa5ca1c66d4d1e
Content-Type: application/json

### login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "test@api.nhe",
    "password": "wwww"
}
###profile
GET http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDYyYzE3ZDY4ZTkxMzZhNDBlMDk5ZCIsImlhdCI6MTU3NzQ4NjQzOH0.NZzOu2sJb4plQ-hCuGZtaoOrccOCgDBaU3o-_KYfwbM

###logout
POST http://localhost:3000/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYzlhYThiZDA3NGVkMTE4ODFkNzliMiIsImlhdCI6MTU3MzQ5NzQ4N30.sCtN5362wkRfj9sL75xh18f3bXGCIoviAJ3jRiyU0Ao

###logoutall
POST http://localhost:3000/user/logoutall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGY3MzEyMTRkN2Q5MjJkYzRmYWEwMiIsImlhdCI6MTU3NDkyNTcwM30.EaY0w_mOuAqIBtaMfiJMneo3ZITGYJDILPbKRmvUuaQ

###

PATCH  http://localhost:3000/user/5dc90f07eec44d19b019b91
Content-Type: application/json

{
    "name": "abcde",
    "email": "abcde@gmail.com"
}
###
POST  http://localhost:3000/product/add
Content-Type: application/json

{
    "name": "a",
    "desc": "aadav dasd adafasdf",
    "price": "1200",
    "rating": "8",
    "qty": "2",
    "imgurl": "./img/test.jpg",
    "category": [{
        "typeOne": "fire"
    },{
        "typeTwo": "water"
    },{
        "typeThree": "pug"
    }]
}
###

GET http://localhost:3000/product
Content-Type: application/json
###
GET http://localhost:3000/product/5dd41961d7b26021689b821b
Content-Type: application/json
###
PATCH  http://localhost:3000/product/5dd41961d7b26021689b821b
Content-Type: application/json

{
    "desc": "123 adad adasda adaas"
}
###
DELETE  http://localhost:3000/product/5dd420b39420db2280e327df
Content-Type: application/json

###
POST http://localhost:3000/order/ntf
Content-Type: application/json